# Complementing a Strand of DNA
# Original problem: http://rosalind.info/problems/revc/
# Solution by Matthew Masters

import numpy as np

dna_data = "ATGTTCCTCCGAACAACCCTGCGGGTTGCCCCTGTCTAAAACACCCCATGCTTGATATTCACGTAAGACCCATGCGAATATGCAAAGTTTAGTAATGGTCTGTGATGTAAAGCCAAGGGCTGTTATAAGCCCTGCGATTTCGGAGCGCCACTGGCCCATGCAAACCATTATAGCGCCATGCTGTCCGATCTTTCCTCAGGTTGGCTCCCTTTGCTTAATAAGCTTGCCATTGTATACCTAATCGTATTATTATTCTGGCGCATCCAAATAAAGTCTTTTCGTGCATTCGTGTAAGTACGGCAAAGCTTTGAGTGAGCGCCCAACGAGCGGAGACCGCGTGTTTCGGAGTTCTGAATGTCCGCGTTTCTGTGTGTCATATAGCTGCAACATCGGCCGAGCTCATAAGTCAGTGAGCTTAAAGGCTAGGGGCCCTTTACTCCAGAACGTTGTTGACTATGGACTGTACGGTGCGCACAGTTAGTGTCATGGAGTCCCACGCAATAAACCCGCTCCTGTGATAACACAACCTTGAATCGTTATTGCACTGCAGGCTTGCGGCTGCGGCGTTGTGCTGTGAATACTCTTCAGACTGATGGATTGTCACTTAGGATCGGTCATCGAGCGACATGCTGTGTGGCCCTCTGGTCAAGACACAGACGCCACTGCTCGCCAGGCGGAACCCTAACAAAAATCTCACCTACTAAAAGCACGATTGGATGCACTGTTGCCCTGCTAGACGCTATAATCTGCTTGGGTCGTGTAGTCAGGAGGTCCGTCCCACCATCTCCACGCATGGTATTGAGGACGGCGGTAAGGGCGCACATGTAATCG"
nucleotides = ['A', 'C', 'G', 'T']

dna_data = dna_data[::-1]
dna_array = np.array(list(dna_data))
complement_array = np.copy(dna_array)

for i,nucleotide in enumerate(nucleotides):
    x = np.argwhere(dna_array==nucleotide)
    complement_array[x] = nucleotides[::-1][i]

print("".join(complement_array))